# fly.toml file generated for dancerush on 2022-10-31T19:21:56+11:00
# To deploy: /mnt/c/Users/Andrew/.fly/bin/fly.exe deploy
app = "dancerush"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  SPRING_DATASOURCE_USERNAME="postgres"
  SPRING_DATASOURCE_URL=${{ secrets.DATABASE_URL }}
  SPRING_DATASOURCE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
  SPRING_JPA_HIBERNATE_DDL_AUTO="validate"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
